import React, { useEffect, useMemo, useState } from 'react';
import api from '../utils/api';
import { BarChart3, ShoppingBag, Users, Store, ArrowUpRight, Plus } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Dashboard(){
 const [a,setA]=useState(null); const [error,setError]=useState('');
 useEffect(()=>{let mounted=true;api.get('/api/analytics/dashboard').then(({data})=>{if(mounted)setA(data.analytics||data.data||{});}).catch(e=>{if(mounted)setError(e.response?.data?.message||'Live analytics are unavailable; showing the dashboard safely.');});return()=>{mounted=false}},[]);
 const cards=[['Total sales',a?`₦${Number(a.revenue||0).toLocaleString()}`:'—','Live',BarChart3],['Orders',a?.orders ?? '—','Live',ShoppingBag],['Customers',a?.customers ?? '—','Live',Users],['Active sellers',a?.sellers ?? '—','Live',Store]];
 const bars=useMemo(()=>[35,48,44,65,52,78,92],[]);
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Overview</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">Good morning, Admin</h1><p className="mt-1 text-sm text-slate-500">Your marketplace performance at a glance.</p></div><Link to="/add" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20"><Plus size={17}/> Add product</Link></div>{error&&<p className="rounded-2xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,change,Icon])=><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm" key={label}><div className="flex items-center justify-between"><span className="rounded-2xl bg-blue-50 p-3 text-blue-600"><Icon size={20}/></span><span className="text-xs font-bold text-emerald-600">{change}</span></div><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-slate-950">{value}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><div><h2 className="font-extrabold">Sales overview</h2><p className="text-sm text-slate-500">Illustrative seven-period view until time-series analytics are connected.</p></div><ArrowUpRight className="text-blue-600"/></div><div className="mt-8 grid h-72 grid-cols-7 items-end gap-3 border-b border-slate-100 pb-2">{bars.map((h,i)=><div key={i} className="flex h-full min-w-0 flex-col items-center justify-end gap-2"><div className="w-full min-h-[10px] rounded-t-xl bg-blue-600" style={{height:`${h}%`}} title={`${h}% illustrative activity`}/><span className="text-xs text-slate-400">{['Mar','Apr','May','Jun','Jul','Aug','Sep'][i]}</span></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-extrabold">Marketplace health</h2><div className="mt-5 space-y-4">{[['Pending seller reviews',a?.pendingSellers ?? '—','Review','/sellers'],['Refund requests',a?.pendingRefunds ?? '—','Review','/refunds'],['Products',a?.products ?? '—','Manage','/list']].map(x=><div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4" key={x[0]}><div><p className="text-sm font-bold">{x[0]}</p><p className="text-2xl font-extrabold text-slate-950">{x[1]}</p></div><Link to={x[3]} className="text-xs font-bold text-blue-600">{x[2]}</Link></div>)}</div></div></div></div>}
