import React, { useEffect, useState } from 'react';
import { CheckCircle2, Eye, FileText, Ban, RotateCcw, Trash2 } from 'lucide-react';
import api from '../utils/api';
import { toast } from 'react-toastify';

export default function Sellers() {
  const [sellers, setSellers] = useState([]);
  const [loading, setLoading] = useState(true);
  const load = async () => { try { const { data } = await api.get('/api/seller?includeDeleted=true'); setSellers(data.sellers || []); } catch(e){ toast.error(e.response?.data?.message || 'Unable to load sellers'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const action = async (url, method='patch', body) => { try { await api({ url, method, data: body }); toast.success('Updated'); load(); } catch(e){ toast.error(e.response?.data?.message || 'Action failed'); } };
  if (loading) return <div className="p-8 text-slate-500">Loading sellers…</div>;
  return <div className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Marketplace</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">Seller approvals</h1><p className="mt-1 text-sm text-slate-500">Review business documents before sellers can operate.</p></div>
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Seller</th><th className="px-5 py-4">Verification</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{sellers.map(s => <tr key={s.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="font-bold text-slate-900">{s.businessName}</div><div className="text-xs text-slate-500">{s.ownerName} · {s.email}</div></td><td className="px-5 py-4">{s.certificate?.url ? <a href={s.certificate.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 font-semibold text-slate-700 hover:border-blue-300"><FileText size={16}/> View certificate <Eye size={14}/></a> : <span className="text-amber-600">Not uploaded</span>}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${s.banned?'bg-red-50 text-red-700':s.deletedAt?'bg-slate-100 text-slate-600':s.status==='approved'?'bg-emerald-50 text-emerald-700':s.status==='suspended'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{s.banned?'Banned':s.deletedAt?'Archived':s.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2">{!s.deletedAt && s.status !== 'approved' && <button onClick={()=>action(`/api/seller/${s.id}/status`,'patch',{status:'approved'})} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 size={14} className="mr-1 inline"/>Approve</button>}{!s.deletedAt && !s.banned && <button onClick={()=>action(`/api/seller/${s.id}/ban`,'patch',{banned:true,reason:'Policy violation'})} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><Ban size={14} className="mr-1 inline"/>Ban</button>}{s.banned && <button onClick={()=>action(`/api/seller/${s.id}/ban`,'patch',{banned:false})} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><RotateCcw size={14} className="mr-1 inline"/>Unban</button>}{!s.deletedAt ? <button onClick={()=>action(`/api/seller/${s.id}`,'delete')} className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:text-red-600"><Trash2 size={16}/></button> : <button onClick={()=>action(`/api/seller/${s.id}/restore`)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><RotateCcw size={14} className="mr-1 inline"/>Restore</button>}</div></td></tr>)}</tbody></table></div></div>
  </div>;
}
