import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Mail, ShieldCheck } from 'lucide-react'
import api from '../utils/api'
import { toast } from 'react-toastify'

export default function ForgotPassword() {
  const [email,setEmail]=useState(''); const [submitting,setSubmitting]=useState(false); const [sent,setSent]=useState(false)
  async function submit(e){e.preventDefault();setSubmitting(true);try{const {data}=await api.post('/api/user/forgot-password',{email});if(!data.success)throw new Error(data.message||'Unable to send reset link');setSent(true)}catch(err){toast.error(err.response?.data?.message||err.message||'Unable to send reset link')}finally{setSubmitting(false)}}
  return <main className="us-shell grid min-h-[calc(100vh-76px)] items-center gap-10 py-10 lg:grid-cols-[1.05fr_.95fr]">
    <section className="hidden overflow-hidden rounded-[32px] bg-[#142b91] p-10 text-white lg:block"><div className="mb-20 flex items-center gap-2 text-sm font-semibold text-blue-100"><ShieldCheck size={18}/> UrbanStep account security</div><h1 className="max-w-lg text-5xl font-extrabold leading-[1.05]">We’ll help you get back in.</h1><p className="mt-5 max-w-md text-blue-100">Request a secure password-reset link for your UrbanStep account.</p><div className="mt-12 space-y-4 text-sm text-blue-50"><p className="flex items-center gap-3"><CheckCircle2 size={18}/> Secure recovery link</p><p className="flex items-center gap-3"><CheckCircle2 size={18}/> No password shared by email</p></div></section>
    <section className="us-panel mx-auto w-full max-w-xl p-6 sm:p-10"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-[#2446e8]">UrbanStep account</span><h2 className="mt-4 text-3xl font-extrabold tracking-tight">Forgot your password?</h2>{sent?<div className="mt-8 rounded-2xl bg-blue-50 p-5 text-sm text-slate-700"><Mail className="mb-3 text-[#2446e8]" size={24}/><p className="font-bold">Check your inbox</p><p className="mt-2">If an account exists for <strong>{email}</strong>, we sent a reset link. Check spam too.</p></div>:<><p className="mt-2 text-sm text-slate-500">Enter your email and we’ll send you a secure reset link.</p><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-semibold">Email address<input className="us-input mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><button disabled={submitting} className="us-button us-button-primary w-full disabled:opacity-60">{submitting?'Sending…':'Send reset link'}<ArrowRight size={18}/></button></form></>}<p className="mt-7 text-center text-sm text-slate-500"><Link to="/login" className="font-bold text-[#2446e8]">Back to sign in</Link></p></section>
  </main>
}
