import React,{useContext,useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {ShopContext} from '../context/ShopContext';
import api from '../utils/api';
import {toast} from 'react-toastify';
import PasswordStrength,{isPasswordValid} from '../components/PasswordStrength';
import GoogleLoginButton from '../components/GoogleLoginButton';

export default function Login(){
 const [mode,setMode]=useState('login'); const [show,setShow]=useState(false); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [loading,setLoading]=useState(false);
 const {token,setToken,navigate}=useContext(ShopContext); const signup=mode==='signup';
 const persist=(data)=>{const access=data.accessToken||data.token||data.data?.accessToken||data.data?.token; if(!access)throw new Error('The server did not return an access token. Check the API response.'); setToken(access); localStorage.setItem('token',access); const refresh=data.refreshToken||data.data?.refreshToken; if(refresh)localStorage.setItem('refreshToken',refresh)};
 useEffect(()=>{if(token)navigate('/')},[token,navigate]);
 async function submit(e){e.preventDefault(); if(signup&&(!isPasswordValid(password)||password!==confirm)){toast.error(password!==confirm?'Passwords do not match':'Use a stronger password');return} setLoading(true); try{const {data}=await api.post(signup?'/api/user/register':'/api/user/login',signup?{name,email,password}:{email,password}); if(!data.success)throw new Error(data.message||'Authentication failed'); persist(data);toast.success(data.message||'Welcome to UrbanStep');navigate('/')}catch(err){toast.error(err.response?.data?.message||err.message||'Unable to sign in')}finally{setLoading(false)}}
 return <main className="us-shell grid min-h-[calc(100vh-76px)] items-center gap-10 py-10 lg:grid-cols-[1.05fr_.95fr]">
  <section className="hidden overflow-hidden rounded-[32px] bg-[#142b91] p-10 text-white lg:block"><div className="mb-20 flex items-center gap-2 text-sm font-semibold text-blue-100"><ShieldCheck size={18}/> Secure shopping, thoughtfully designed</div><h1 className="max-w-lg text-5xl font-extrabold leading-[1.05]">Your next favorite look is waiting.</h1><p className="mt-5 max-w-md text-blue-100">Discover expressive fashion from trusted sellers, with a seamless checkout and a marketplace built around you.</p><div className="mt-12 space-y-4 text-sm text-blue-50"><p className="flex items-center gap-3"><CheckCircle2 size={18}/> Curated fashion from independent sellers</p><p className="flex items-center gap-3"><CheckCircle2 size={18}/> Secure account and order tracking</p><p className="flex items-center gap-3"><CheckCircle2 size={18}/> One basket, many possibilities</p></div></section>
  <section className="us-panel mx-auto w-full max-w-xl p-6 sm:p-10"><div className="mb-8"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-[#2446e8]">UrbanStep account</span><h2 className="mt-4 text-3xl font-extrabold tracking-tight">{signup?'Create your account':'Welcome back'}</h2><p className="mt-2 text-sm text-slate-500">{signup?'Join the community shaping everyday style.':'Sign in to continue your shopping journey.'}</p></div>
   <form onSubmit={submit} className="space-y-4">{signup&&<label className="block text-sm font-semibold">Full name<input className="us-input mt-2" value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label>}<label className="block text-sm font-semibold">Email address<input className="us-input mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label className="block text-sm font-semibold">Password<div className="relative mt-2"><input className="us-input pr-12" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{signup&&<><PasswordStrength password={password}/><label className="block text-sm font-semibold">Confirm password<input className="us-input mt-2" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required placeholder="Repeat your password"/></label></>} {!signup&&<div className="text-right"><button type="button" onClick={()=>navigate('/forgot-password')} className="text-sm font-semibold text-[#2446e8]">Forgot password?</button></div>}<button disabled={loading} className="us-button us-button-primary w-full disabled:cursor-not-allowed disabled:opacity-60">{loading?'Please wait…':signup?'Create account':'Sign in'}<ArrowRight size={18}/></button></form>
   <div className="my-6 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>OR<span className="h-px flex-1 bg-slate-200"/></div><GoogleLoginButton/><p className="mt-7 text-center text-sm text-slate-500">{signup?'Already have an account?':'New to UrbanStep?'} <button onClick={()=>setMode(signup?'login':'signup')} className="font-bold text-[#2446e8]">{signup?'Sign in':'Create an account'}</button></p>
  </section></main>
}
